// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetcore_crud.Data;

#nullable disable

namespace aspnetcore_crud.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("aspnetcore_crud.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AccountId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountType = "Domestic",
                            DateCreated = new DateTime(2003, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 1
                        },
                        new
                        {
                            Id = 2,
                            AccountType = "Domestic",
                            DateCreated = new DateTime(1996, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 2
                        },
                        new
                        {
                            Id = 3,
                            AccountType = "Domestic",
                            DateCreated = new DateTime(1999, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 3
                        },
                        new
                        {
                            Id = 4,
                            AccountType = "Savings",
                            DateCreated = new DateTime(1999, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 3
                        },
                        new
                        {
                            Id = 5,
                            AccountType = "Domestic",
                            DateCreated = new DateTime(2010, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 4
                        },
                        new
                        {
                            Id = 6,
                            AccountType = "Foreign",
                            DateCreated = new DateTime(1999, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 3
                        },
                        new
                        {
                            Id = 7,
                            AccountType = "Foreign",
                            DateCreated = new DateTime(1996, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 2
                        },
                        new
                        {
                            Id = 8,
                            AccountType = "Foreign",
                            DateCreated = new DateTime(2010, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerId = 4
                        });
                });

            modelBuilder.Entity("aspnetcore_crud.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OwnerId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("owners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Phan Châu Trinh",
                            DateOfBirth = new DateTime(1978, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nguyễn Văn A"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Phan Bội Châu",
                            DateOfBirth = new DateTime(1985, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Trần Văn B"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Ngô Quyền",
                            DateOfBirth = new DateTime(1970, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nguyễn Thị C"
                        },
                        new
                        {
                            Id = 4,
                            Address = "1010 Nguyễn Trãi",
                            DateOfBirth = new DateTime(1992, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nguyễn Thị D"
                        });
                });

            modelBuilder.Entity("aspnetcore_crud.Models.Account", b =>
                {
                    b.HasOne("aspnetcore_crud.Models.Owner", "Owner")
                        .WithMany("Accounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("aspnetcore_crud.Models.Owner", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
